# Generated by Django 3.1.3 on 2020-11-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_numbe',
            new_name='phone_number',
        ),
    ]
